server:
  port: 80

spring:
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp

  mail:
    host: smtp.gmail.com
    port: 587
    username: uhyeon1009@gmail.com
    password: jbplojrtsdidnxsy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 3m

  datasource:
    hikari:
      pool-name: HikariPool
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/trip?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
      username: ssafy
      password: ssafy1234
      max-lifetime: 1800000
      idle-timeout: 600000
      auto-commit: true
      connection-timeout: 5000
      minimum-idle: 30
      maximum-pool-size: 30

  data:
    redis:
      host: localhost
      port: 6379

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

mybatis:
  type-aliases-package: com.ssafy.**.model
  type-handlers-package: com.ssafy.**.model.typehandlers
  mybatis.mapper-locations: mapper/*.xml

logging:
  level:
    com:
      ssafy: debug
      root: info
#      zaxxer.hikari.pool.HikariPool: debug

jwt:
  secret-key: test-key
  accessToken:
    expire-time: 10s
  refreshToken:
    expire-time: 2h